### ISSUE TITLE
Travis fails on `bower install`

### ISSUE THREAD

**Issue by ptolemybarnes** [makersacademy/todo_challenge#68]
Probably `npm install -g bower` needs to be added to the before_script in the .travis.yml.

**Comment by zdajani** [comment]
`npm install --save-dev bower` to add it as a dependancy to the package.json and `"postinstall": "bower cache clean && bower install"` in the scripts of the package.json

And then add `bower install` in the before_script of the travis.yml

though you will probably encounter issues with your karma and protractor tests unless you set them up properly in the scripts of the package.json

**Comment by lroliphant** [comment]
Hi, thanks for tips. I put them both in but it still doesn't seem to work.

**Comment by ptolemybarnes** [comment]
@katsuraku lent me her todo_challenge to figure this out... took a while. Here's the diff (see inline comment for clarifications):

``` git
diff --git a/package.json b/package.json
index 659b717..83cc6d2 100644
--- a/package.json
+++ b/package.json
@@ -4,7 +4,8 @@
   "description": "* Deadline: submit completed pull request by 9am on Monday * You may use whatever level of JavaScript you feel comfortable with - pure JS, jQuery, Angular, or whatever weird and wonderful framework you want to try. Extra points for DogeScript",
   "main": "index.js",
   "scripts": {
-    "test": "echo \"Error: no test specified\" && exit 1"
+    "test": "karma start test/karma.conf.js", # specify the test script
+    "postinstall": "bower cache clean && bower install" # this is needed.. not totally sure why.
   },
   "repository": {
     "type": "git",
@@ -17,6 +18,7 @@
   },
   "homepage": "https://github.com/katsuraku/todo_challenge",
   "devDependencies": {
+    "bower": "^1.4.1", # list bower as a dependency with "npm install --save-dev bower"
     "jasmine-core": "^2.3.4",
     "karma": "^0.13.3",
     "karma-chrome-launcher": "^0.2.0",

diff --git a/test/karma.conf.js b/test/karma.conf.js
index e0998ae..90a3e68 100644
--- a/test/karma.conf.js
+++ b/test/karma.conf.js
@@ -63,6 +63,6 @@ module.exports = function(config) {

     // Continuous Integration mode
     // if true, Karma captures browsers, runs the tests and exits
-    singleRun: false
+    singleRun: true # travis CI doesn't like sunRun: false
   });
 };
```

**Comment by spike01** [comment]
`cache clean` is technically correct but not always necessary. The key things are to have bower listed as a dev dependency and to have a postinstall script

**Comment by lroliphant** [comment]
Amended and pushed - that worked. Thanks all

**Comment by natstar93** [comment]
Thanks @zdajani and others! Mine is working now. Sticker please ;)
